lib/web/router.ex
defmodule Web.Router do
  use Web, :router

  @report_errors Application.get_env(:ex_venture, :errors)[:report]

  if @report_errors do
    use Plug.ErrorHandler
    use Sentry.Plug
  end

  pipeline :browser do
    plug(:accepts, ["html", "json"])
    plug(:fetch_session)
    plug(:fetch_flash)
    plug(:protect_from_forgery)
    plug(:put_secure_browser_headers)
  end

  pipeline :public do
    plug(Web.Plug.LoadUser)
  end

  pipeline :public_2fa do
    plug(Web.Plug.LoadUser, verify: false)
  end

  scope "/", Web, as: :public do
    pipe_through([:browser, :public_2fa])

    get("/account/twofactor/verify", AccountTwoFactorController, :verify)
    post("/account/twofactor/verify", AccountTwoFactorController, :verify_token)
  end

  scope "/", Web, as: :public do
    pipe_through([:browser, :public])

    get("/css/colors.css", ColorController, :index)
    get("/clients/mudlet/ex_venture.xml", PageController, :mudlet_package)
    get("/clients/map.xml", PageController, :map)

    get("/", PageController, :index)
    get("/version", PageController, :version)

    get("/account", AccountController, :show)
    put("/account", AccountController, :update)

    get("/account/twofactor/start", AccountTwoFactorController, :start)
    get("/account/twofactor/qr.png", AccountTwoFactorController, :qr)
    post("/account/twofactor", AccountTwoFactorController, :validate)
    delete("/account/twofactor", AccountTwoFactorController, :clear)

    resources("/account/mail", MailController, only: [:index, :show, :new, :create])

    get("/announcements/atom", AnnouncementController, :feed)
    resources("/announcements", AnnouncementController, only: [:show])

    get("/chat", ChatController, :show)

    resources("/classes", ClassController, only: [:index, :show])

    get("/connection/authorize", ConnectionController, :authorize)
    post("/connection/authorize", ConnectionController, :connect)

    get("/help/commands", HelpController, :commands)
    get("/help/commands/:command", HelpController, :command)
    resources("/help", HelpController, only: [:index, :show])
    get("/help/builtin/:id", HelpController, :built_in)

    get("/play", PlayController, :show)

    resources("/races", RaceController, only: [:index, :show])

    get("/register/reset", RegistrationResetController, :new)
    post("/register/reset", RegistrationResetController, :create)

    get("/register/reset/verify", RegistrationResetController, :edit)
    post("/register/reset/verify", RegistrationResetController, :update)

    resources("/register", RegistrationController, only: [:new, :create])

    delete("/sessions", SessionController, :delete)
    resources("/sessions", SessionController, only: [:new, :create])

    resources("/skills", SkillController, only: [:index, :show])

    get("/who", PageController, :who)
  end

  scope "/admin", Web.Admin do
    pipe_through(:browser)

    get("/", DashboardController, :index)

    resources("/announcements", AnnouncementController, except: [:delete])

    resources "/bugs", BugController, only: [:index, :show] do
      post("/complete", BugController, :complete, as: :complete)
    end

    resources("/channels", ChannelController, only: [:index, :new, :show, :create, :edit, :update])

    resources "/classes", ClassController, only: [:index, :show, :new, :create, :edit, :update] do
      resources("/skills", ClassSkillController, only: [:new, :create], as: :skill)
    end

    resources("/class_skills", ClassSkillController, only: [:delete])

    get("/colors", ColorController, :index)
    post("/colors", ColorController, :update)
    delete("/colors", ColorController, :delete)

    resources("/color_codes", ColorCodeController, only: [:new, :create, :edit, :update])

    resources("/config", ConfigController, only: [:index, :edit, :update])

    resources("/damage_types", DamageTypeController, except: [:show, :delete])

    resources("/exits", RoomExitController, only: [:delete], as: :exit)

    resources(
      "/help_topics",
      HelpTopicController,
      only: [:index, :show, :new, :create, :edit, :update]
    )

    resources("/insights", InsightController, only: [:index])

    resources "/items", ItemController, only: [:index, :show, :edit, :update, :new, :create] do
      resources("/aspects", ItemAspectingController, only: [:new, :create], as: :aspecting)
    end

    resources(
      "/item_aspects",
      ItemAspectController,
      only: [:index, :show, :edit, :update, :new, :create]
    )

    resources("/item_aspectings", ItemAspectingController, only: [:delete])

    resources("/notes", NoteController, only: [:index, :show, :new, :create, :edit, :update])

    resources "/npcs", NPCController, only: [:index, :show, :edit, :update, :new, :create] do
      post("/events/reload", NPCEventController, :reload)

      resources("/events", NPCEventController, except: [:show], as: :event)

      resources("/items", NPCItemController, only: [:new, :create], as: :item)

      get "/script", NPCScriptController, :show, as: :script
      get "/script/edit", NPCScriptController, :edit, as: :script
      put "/script", NPCScriptController, :update, as: :script

      resources("/skills", NPCSkillController, only: [:new, :create, :delete], as: :skill)

      resources("/spawners", NPCSpawnerController, only: [:new, :create], as: :spawner)
    end

    resources("/npc_items", NPCItemController, only: [:edit, :update, :delete])

    resources("/npc_spawners", NPCSpawnerController, only: [:show, :edit, :update, :delete])

    resources("/quest_relations", QuestRelationController, only: [:delete])

    resources("/quest_steps", QuestStepController, only: [:edit, :update, :delete])

    resources "/quests", QuestController, only: [:index, :show, :new, :create, :edit, :update] do
      resources("/relations", QuestRelationController, only: [:new, :create], as: :relation)

      resources("/steps", QuestStepController, only: [:new, :create], as: :step)
    end

    resources "/races", RaceController, only: [:index, :show, :new, :create, :edit, :update] do
      resources("/skills", RaceSkillController, only: [:new, :create], as: :skill)
    end

    resources("/race_skills", RaceSkillController, only: [:delete])

    resources("/room_items", RoomItemController, only: [:delete])

    resources "/rooms", RoomController, only: [:show, :edit, :update, :delete] do
      resources("/exits", RoomExitController, only: [:new, :create], as: :exit)

      resources(
        "/features",
        RoomFeatureController,
        only: [:new, :create, :edit, :update, :delete],
        as: :feature
      )

      resources("/items", RoomItemController, only: [:new, :create])

      resources("/shops", ShopController, only: [:new, :create])
    end

    resources("/sessions", SessionController, only: [:new, :create])

    resources("/shop_items", ShopItemController, only: [:edit, :update, :delete])

    resources "/shops", ShopController, only: [:show, :edit, :update] do
      resources("/items", ShopItemController, only: [:new, :create])
    end

    resources("/skills", SkillController, only: [:index, :show, :new, :create, :edit, :update])

    resources("/socials", SocialController, only: [:index, :show, :new, :create, :edit, :update])

    resources("/typos", TypoController, only: [:index, :show])

    post("/users/teleport", UserController, :teleport)
    post("/users/disconnect", UserController, :disconnect)

    resources "/users", UserController, only: [:index, :show, :edit, :update] do
      get("/cheat", UserController, :cheat, as: :cheat)
      post("/cheat/activate", UserController, :cheating, as: :cheating)
      post("/reset", UserController, :reset, as: :reset)
      get("/watch", UserController, :watch, as: :watch)
    end

    resources "/zones", ZoneController, only: [:index, :show, :new, :create, :edit, :update] do
      resources("/rooms", RoomController, only: [:new, :create])
    end
  end

  if Mix.env() == :dev do
    forward("/emails/sent", Bamboo.EmailPreviewPlug)
  end
end

lib/web/templates/page/_announcements.html.eex
<%= if length(@announcements) > 0 do %>
  <h3>Announcements</h3>
  <ul class="list-group">
    <%= Enum.map(@announcements, fn announcement -> %>
      <li class="list-group-item">
        <div class="d-flex w-100 justify-content-between">
          <h5 class="mb-1">
            <%= if announcement.is_sticky do %>
              <span class="small"><i class="fas fa-thumbtack"></i></span>
            <% end %>
            <%= link(announcement.title, to: public_announcement_path(@conn, :show, announcement.uuid)) %>
          </h5>
          <small><%= TimeView.relative(announcement.published_at) %></small>
        </div>
      </li>
    <% end) %>
  </ul>
<% end %>

lib/web/templates/page/index.html.eex
<div class="row">
  <div class="col-md-6 text-center text-md-left">
    <h1 class="mb-3"><%= Config.game_name() %></h1>

    <p>
      Connect with telnet: <code><%= Config.host() %>:<%= Config.port() %></code>
    </p>

    <%= if Config.ssl?() do %>
      <p>
        Connect with a TLS client: <code><%= Config.host() %>:<%= Config.ssl_port() %></code>
      </p>
    <% end %>

    <%= if !Map.has_key?(@conn.assigns, :user) do %>
      <p>
        <%= link("Sign in", to: public_session_path(@conn, :new)) %> before playing to start right away. You can also <%= link("create a new account", to: public_registration_path(@conn, :new)) %> to start playing.
      </p>
    <% end %>

    <%= link(to: public_play_path(@conn, :show), class: "btn btn-lg btn-primary") do %>
      Play Now &raquo;
    <% end %>
  </div>

  <div class="col-md-6">
    <%= render("_announcements.html", conn: @conn, announcements: @announcements) %>
  </div>
</div>

lib/web/templates/page/map.xml.eex
<?xml version="1.0"?>
<map>
  <areas>
    <%= Enum.map(@zones, fn zone -> %>
    <area id="<%= zone.id %>" name="<%= xml_escape(zone.name) %>" />
    <% end) %>
  </areas>
  <rooms>
<%= Enum.map(@zones, fn zone -> %>
  <%= Enum.map(Room.for_map(zone), fn room -> %>
    <room id="<%= room.id %>" area="<%= zone.id %>" title="<%= xml_escape(room.name) %>" environment="<%= Room.ecology_id(room) + 1 %>">
      <coord x="<%= room.x %>" y="<%= room.y * -1 %>" z="<%= room.map_layer %>" />
    <%= Enum.map(room.exits, fn room_exit -> %>
      <exit direction="<%= room_exit.direction %>" target="<%= room_exit.finish_id %>" />
    <% end) %>
    </room>
  <% end) %>
<% end )%>
  </rooms>
  <environments>
  <%= Enum.map(Room.ecologies(), fn {ecology, id} -> %>
    <environment id="<%= id + 1 %>" name="<%= ecology %>" color="<%= Room.ecology_color_id(ecology) %>" />
  <% end) %>
  </environments>
</map>

lib/web/templates/page/who.html.eex
<div class="row align-items-center">
  <div class="col-md-6 text-center text-md-left">
    <h1 class="mb-3">Connected Players</h1>
    <ul class="list-group">
      <%= Enum.map(@players, fn (player) -> %>
        <li class="list-group-item"><%= player.name %></li>
      <% end) %>
    </ul>
  </div>
</div>