lib/web/router.ex
defmodule Web.Router do
  use Web, :router

  @report_errors Application.get_env(:ex_venture, :errors)[:report]

  if @report_errors do
    use Plug.ErrorHandler
    use Sentry.Plug
  end

  pipeline :browser do
    plug(:accepts, ["html", "json"])
    plug(:fetch_session)
    plug(:fetch_flash)
    plug(:protect_from_forgery)
    plug(:put_secure_browser_headers)
  end

  pipeline :public do
    plug(Web.Plug.LoadUser)
  end

  pipeline :public_2fa do
    plug(Web.Plug.LoadUser, verify: false)
  end

  scope "/", Web, as: :public do
    pipe_through([:browser, :public_2fa])

    get("/account/twofactor/verify", AccountTwoFactorController, :verify)
    post("/account/twofactor/verify", AccountTwoFactorController, :verify_token)
  end

  scope "/", Web, as: :public do
    pipe_through([:browser, :public])

    get("/css/colors.css", ColorController, :index)
    get("/clients/mudlet/ex_venture.xml", PageController, :mudlet_package)
    get("/clients/map.xml", PageController, :map)

    get("/", PageController, :index)
    get("/version", PageController, :version)

    get("/account", AccountController, :show)
    put("/account", AccountController, :update)

    get("/account/twofactor/start", AccountTwoFactorController, :start)
    get("/account/twofactor/qr.png", AccountTwoFactorController, :qr)
    post("/account/twofactor", AccountTwoFactorController, :validate)
    delete("/account/twofactor", AccountTwoFactorController, :clear)

    resources("/account/mail", MailController, only: [:index, :show, :new, :create])

    get("/announcements/atom", AnnouncementController, :feed)
    resources("/announcements", AnnouncementController, only: [:show])

    get("/chat", ChatController, :show)

    resources("/classes", ClassController, only: [:index, :show])

    get("/connection/authorize", ConnectionController, :authorize)
    post("/connection/authorize", ConnectionController, :connect)

    get("/help/commands", HelpController, :commands)
    get("/help/commands/:command", HelpController, :command)
    resources("/help", HelpController, only: [:index, :show])
    get("/help/builtin/:id", HelpController, :built_in)

    get("/play", PlayController, :show)

    resources("/races", RaceController, only: [:index, :show])

    get("/register/reset", RegistrationResetController, :new)
    post("/register/reset", RegistrationResetController, :create)

    get("/register/reset/verify", RegistrationResetController, :edit)
    post("/register/reset/verify", RegistrationResetController, :update)

    resources("/register", RegistrationController, only: [:new, :create])

    delete("/sessions", SessionController, :delete)
    resources("/sessions", SessionController, only: [:new, :create])

    resources("/skills", SkillController, only: [:index, :show])

    get("/who", PageController, :who)
  end

  scope "/admin", Web.Admin do
    pipe_through(:browser)

    get("/", DashboardController, :index)

    resources("/announcements", AnnouncementController, except: [:delete])

    resources "/bugs", BugController, only: [:index, :show] do
      post("/complete", BugController, :complete, as: :complete)
    end

    resources("/channels", ChannelController, only: [:index, :new, :show, :create, :edit, :update])

    resources "/classes", ClassController, only: [:index, :show, :new, :create, :edit, :update] do
      resources("/skills", ClassSkillController, only: [:new, :create], as: :skill)
    end

    resources("/class_skills", ClassSkillController, only: [:delete])

    get("/colors", ColorController, :index)
    post("/colors", ColorController, :update)
    delete("/colors", ColorController, :delete)

    resources("/color_codes", ColorCodeController, only: [:new, :create, :edit, :update])

    resources("/config", ConfigController, only: [:index, :edit, :update])

    resources("/damage_types", DamageTypeController, except: [:show, :delete])

    resources("/exits", RoomExitController, only: [:delete], as: :exit)

    resources(
      "/help_topics",
      HelpTopicController,
      only: [:index, :show, :new, :create, :edit, :update]
    )

    resources("/insights", InsightController, only: [:index])

    resources "/items", ItemController, only: [:index, :show, :edit, :update, :new, :create] do
      resources("/aspects", ItemAspectingController, only: [:new, :create], as: :aspecting)
    end

    resources(
      "/item_aspects",
      ItemAspectController,
      only: [:index, :show, :edit, :update, :new, :create]
    )

    resources("/item_aspectings", ItemAspectingController, only: [:delete])

    resources("/notes", NoteController, only: [:index, :show, :new, :create, :edit, :update])

    resources "/npcs", NPCController, only: [:index, :show, :edit, :update, :new, :create] do
      post("/events/reload", NPCEventController, :reload)

      resources("/events", NPCEventController, except: [:show], as: :event)

      resources("/items", NPCItemController, only: [:new, :create], as: :item)

      get "/script", NPCScriptController, :show, as: :script
      get "/script/edit", NPCScriptController, :edit, as: :script
      put "/script", NPCScriptController, :update, as: :script

      resources("/skills", NPCSkillController, only: [:new, :create, :delete], as: :skill)

      resources("/spawners", NPCSpawnerController, only: [:new, :create], as: :spawner)
    end

    resources("/npc_items", NPCItemController, only: [:edit, :update, :delete])

    resources("/npc_spawners", NPCSpawnerController, only: [:show, :edit, :update, :delete])

    resources("/quest_relations", QuestRelationController, only: [:delete])

    resources("/quest_steps", QuestStepController, only: [:edit, :update, :delete])

    resources "/quests", QuestController, only: [:index, :show, :new, :create, :edit, :update] do
      resources("/relations", QuestRelationController, only: [:new, :create], as: :relation)

      resources("/steps", QuestStepController, only: [:new, :create], as: :step)
    end

    resources "/races", RaceController, only: [:index, :show, :new, :create, :edit, :update] do
      resources("/skills", RaceSkillController, only: [:new, :create], as: :skill)
    end

    resources("/race_skills", RaceSkillController, only: [:delete])

    resources("/room_items", RoomItemController, only: [:delete])

    resources "/rooms", RoomController, only: [:show, :edit, :update, :delete] do
      resources("/exits", RoomExitController, only: [:new, :create], as: :exit)

      resources(
        "/features",
        RoomFeatureController,
        only: [:new, :create, :edit, :update, :delete],
        as: :feature
      )

      resources("/items", RoomItemController, only: [:new, :create])

      resources("/shops", ShopController, only: [:new, :create])
    end

    resources("/sessions", SessionController, only: [:new, :create])

    resources("/shop_items", ShopItemController, only: [:edit, :update, :delete])

    resources "/shops", ShopController, only: [:show, :edit, :update] do
      resources("/items", ShopItemController, only: [:new, :create])
    end

    resources("/skills", SkillController, only: [:index, :show, :new, :create, :edit, :update])

    resources("/socials", SocialController, only: [:index, :show, :new, :create, :edit, :update])

    resources("/typos", TypoController, only: [:index, :show])

    post("/users/teleport", UserController, :teleport)
    post("/users/disconnect", UserController, :disconnect)

    resources "/users", UserController, only: [:index, :show, :edit, :update] do
      get("/cheat", UserController, :cheat, as: :cheat)
      post("/cheat/activate", UserController, :cheating, as: :cheating)
      post("/reset", UserController, :reset, as: :reset)
      get("/watch", UserController, :watch, as: :watch)
    end

    resources "/zones", ZoneController, only: [:index, :show, :new, :create, :edit, :update] do
      resources("/rooms", RoomController, only: [:new, :create])
    end
  end

  if Mix.env() == :dev do
    forward("/emails/sent", Bamboo.EmailPreviewPlug)
  end
end

lib/web/controllers/help_controller.ex
defmodule Web.HelpController do
  use Web, :controller

  alias Game.Help
  alias Web.HelpTopic

  def index(conn, _params) do
    help_topics = HelpTopic.all(alpha: true)
    conn
    |> assign(:help_topics, help_topics)
    |> render("index.html")
  end

  def show(conn, %{"id" => id}) do
    case HelpTopic.get(id) do
      nil ->
        conn |> redirect(to: public_page_path(conn, :index))

      help_topic ->
        conn |> render("show.html", help_topic: help_topic)
    end
  end

  def commands(conn, _params) do
    commands = HelpTopic.commands()

    conn
    |> assign(:commands, commands)
    |> render("commands.html")
  end

  def command(conn, %{"command" => command}) do
    with {:ok, command} <- HelpTopic.command(command),
         :ok <- check_user_allowed(conn, command) do
      conn
      |> assign(:command, command)
      |> render("command.html")
    else
      _ ->
        conn |> redirect(to: public_page_path(conn, :index))
    end
  end

  def built_in(conn, %{"id" => id}) do
    case HelpTopic.built_in(id) do
      nil ->
        conn |> redirect(to: public_page_path(conn, :index))

      built_in ->
        conn |> render("built_in.html", built_in: built_in)
    end
  end

  defp check_user_allowed(conn, command) do
    flags =
      conn.assigns
      |> Map.get(:user, %{})
      |> Map.get(:flags, [])

    case Help.allowed?(command, flags) do
      true ->
        :ok

      false ->
        {:error, :not_allowed}
    end
  end
end

lib/web/views/help_view.ex
defmodule Web.HelpView do
  use Web, :view

  alias Game.Help.BuiltIn
  alias Web.Color

  def command_topic_key(command) do
    command |> to_string |> String.split(".") |> List.last()
  end
end

lib/web/templates/help/built_in.html.eex
<div class="row">
  <div class="col-md-12">
    <h2 class="mb-3"><%= @built_in.name %></h2>
    <p>
      <pre class="terminal">
        <%= @built_in.full |> Color.format() |> String.replace("\n", "<br />") |> raw() %>
      </pre>
    </p>
  </div>
</div>

<div class="row">
  <div class="col-md-12">
    <div class="back">
      <%= link(to: public_help_path(@conn, :index), class: "back") do %>
        &laquo; Back
      <% end %>
    </div>
  </div>
</div>

lib/web/templates/help/command.html.eex
<div class="row">
  <div class="col-md-12">
    <h2 class="mb-3"><%= @command |> command_topic_key() %></h2>
    <p>
      Commands:
      <%= Enum.map(@command.commands(), fn (command) -> %>
        <code><%= command %></code>
      <% end) %>
    </p>
    <%= if @command.aliases |> length() > 0 do %>
      <p>
        Aliases:
        <%= Enum.map(@command.aliases(), fn (alias) -> %>
          <code><%= alias %></code>
        <% end) %>
      </p>
    <% end %>
    <p>
      <pre class="terminal">
        <%= @command.help(:full) |> Color.format() |> String.replace("\n", "<br />") |> raw() %>
      </pre>
    </p>
  </div>
</div>

<div class="row">
  <div class="col-md-12">
    <div class="back">
      <%= link(to: public_help_path(@conn, :commands), class: "back") do %>
        &laquo; Back
      <% end %>
    </div>
  </div>
</div>

lib/web/templates/help/commands.html.eex
<div class="row align-items-center">
  <div class="col-md-12">
    <h1 class="mb-3">Help Commands</h1>
    <ul class="list-group">
      <%= Enum.map(@commands, fn (command) -> %>
        <li class="list-group-item">
          <%= link(command, to: public_help_path(@conn, :command, command |> String.downcase)) %>
        </li>
      <% end) %>
    </ul>
  </div>
</div>

lib/web/templates/help/index.html.eex
<div class="row align-items-center">
  <div class="col-md-12">
    <h1 class="mb-3">Help Topics</h1>
    <ul class="list-group">
      <li class="list-group-item">
        <%= link("Commands", to: public_help_path(@conn, :commands)) %>
      </li>
      <%= Enum.map(@help_topics, fn (help_topic) -> %>
        <li class="list-group-item">
          <%= case help_topic do %>
            <% %BuiltIn{} -> %>
              <%= link(help_topic.name, to: public_help_path(@conn, :built_in, help_topic.id)) %>
            <% _ -> %>
              <%= link(help_topic.name, to: public_help_path(@conn, :show, help_topic.id)) %>
          <% end %>
        </li>
      <% end) %>
    </ul>
  </div>
</div>

lib/web/templates/help/show.html.eex
<div class="row">
  <div class="col-md-12">
    <h2 class="mb-3"><%= @help_topic.name %></h2>
    <span>Keywords: <%= @help_topic.keywords |> Enum.join(", ") %></span>
    <p><%= @help_topic.body %></p>
  </div>
</div>

<div class="row">
  <div class="col-md-12">
    <div class="back">
      <%= link(to: public_help_path(@conn, :index)) do %>
        &laquo; Back
      <% end %>
    </div>
  </div>
</div>